// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Lexer.flex


import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\4\0\1\6\1\0\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\6\20\3\21\1\22"+
    "\1\23\1\24\1\25\1\26\2\0\1\27\1\30\1\31"+
    "\1\32\1\33\1\30\1\34\1\30\1\35\1\30\1\36"+
    "\1\37\1\40\1\41\1\42\4\30\1\43\6\30\1\44"+
    "\1\0\1\45\1\0\1\46\1\0\1\47\1\30\1\50"+
    "\1\51\1\52\1\53\1\54\1\30\1\55\1\56\1\30"+
    "\1\57\1\60\1\61\1\62\1\63\1\30\1\64\1\65"+
    "\1\66\1\67\1\70\1\30\1\71\2\30\1\72\1\73"+
    "\1\74\7\0\1\3\113\0\1\30\17\0\1\30\7\0"+
    "\1\30\3\0\1\30\3\0\1\30\1\0\1\30\6\0"+
    "\1\30\u012d\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\14\1\15\1\16\1\17"+
    "\1\1\1\20\7\21\1\22\1\23\10\21\1\24\1\3"+
    "\1\25\1\26\1\27\1\30\1\0\1\2\1\0\2\31"+
    "\1\32\1\33\1\34\1\35\5\21\1\36\12\21\1\37"+
    "\2\0\1\32\2\21\1\40\2\21\1\36\13\21\1\0"+
    "\1\2\1\21\1\41\13\21\1\37\5\21\1\42\1\21"+
    "\1\43\2\21\1\44\10\21\1\45\1\46\4\21\1\47"+
    "\1\50\16\21\1\51\1\21\1\52\1\53\3\21\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\75\0\172\0\267\0\364\0\75\0\75"+
    "\0\75\0\75\0\75\0\u0131\0\75\0\u016e\0\u01ab\0\u01e8"+
    "\0\75\0\75\0\u0225\0\u0262\0\u029f\0\u02dc\0\u0319\0\u0356"+
    "\0\u0393\0\u03d0\0\u040d\0\u044a\0\75\0\75\0\u0487\0\u04c4"+
    "\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632\0\75\0\75"+
    "\0\75\0\75\0\u066f\0\75\0\u06ac\0\u06e9\0\u0726\0\75"+
    "\0\u0763\0\u07a0\0\75\0\75\0\75\0\u07dd\0\u081a\0\u0857"+
    "\0\u0894\0\u08d1\0\75\0\u090e\0\u094b\0\u0988\0\u09c5\0\u0a02"+
    "\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33\0\u0b70\0\u0bad\0\u0bea"+
    "\0\75\0\u0c27\0\u0c64\0\u02dc\0\u0ca1\0\u0cde\0\u0d1b\0\u0d58"+
    "\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89\0\u0ec6\0\u0f03\0\u0f40"+
    "\0\u0f7d\0\u0fba\0\u0ff7\0\u0bad\0\u1034\0\75\0\u1071\0\u10ae"+
    "\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df\0\u121c\0\u1259\0\u1296"+
    "\0\u12d3\0\u02dc\0\u1310\0\u134d\0\u138a\0\u13c7\0\u1404\0\u02dc"+
    "\0\u1441\0\u02dc\0\u147e\0\u14bb\0\u02dc\0\u14f8\0\u1535\0\u1572"+
    "\0\u15af\0\u15ec\0\u1629\0\u1666\0\u16a3\0\u02dc\0\u02dc\0\u16e0"+
    "\0\u171d\0\u175a\0\u1797\0\u17d4\0\u02dc\0\u1811\0\u184e\0\u188b"+
    "\0\u18c8\0\u1905\0\u1942\0\u197f\0\u19bc\0\u19f9\0\u1a36\0\u1a73"+
    "\0\u1ab0\0\u1aed\0\u1b2a\0\u02dc\0\u1b67\0\u02dc\0\u02dc\0\u1ba4"+
    "\0\u1be1\0\u1c1e\0\u02dc";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\2\20"+
    "\1\21\1\22\1\23\1\24\1\25\2\26\1\27\1\30"+
    "\1\31\2\26\1\32\1\33\3\26\1\34\1\35\1\36"+
    "\1\26\1\37\2\26\1\40\1\41\1\42\1\43\2\26"+
    "\1\44\3\26\1\45\1\46\4\26\1\47\1\50\1\51"+
    "\77\0\1\3\117\0\1\52\76\0\15\53\2\0\24\53"+
    "\20\0\1\54\70\0\1\55\4\0\1\56\73\0\1\57"+
    "\1\0\1\60\2\61\70\0\1\62\1\0\3\20\100\0"+
    "\1\63\74\0\1\64\74\0\1\65\66\0\3\26\5\0"+
    "\15\26\2\0\24\26\22\0\3\26\5\0\1\66\14\26"+
    "\2\0\24\26\22\0\3\26\5\0\4\26\1\67\10\26"+
    "\2\0\24\26\22\0\3\26\5\0\12\26\1\70\2\26"+
    "\2\0\24\26\22\0\3\26\5\0\15\26\2\0\1\71"+
    "\23\26\22\0\3\26\5\0\13\26\1\72\1\26\2\0"+
    "\24\26\20\0\1\73\1\0\1\26\2\74\5\0\15\26"+
    "\2\0\24\26\22\0\3\26\5\0\15\26\2\0\2\26"+
    "\1\75\21\26\22\0\3\26\5\0\15\26\2\0\22\26"+
    "\1\76\1\77\22\0\3\26\5\0\15\26\2\0\1\26"+
    "\1\100\5\26\1\101\14\26\22\0\3\26\5\0\15\26"+
    "\2\0\4\26\1\102\17\26\22\0\3\26\5\0\15\26"+
    "\2\0\13\26\1\103\10\26\22\0\3\26\5\0\15\26"+
    "\2\0\21\26\1\104\2\26\22\0\3\26\5\0\15\26"+
    "\2\0\4\26\1\105\17\26\22\0\3\26\5\0\15\26"+
    "\2\0\7\26\1\106\14\26\22\0\3\53\5\0\15\53"+
    "\2\0\24\53\3\0\11\107\1\110\63\107\2\56\1\3"+
    "\1\56\1\4\70\56\17\0\1\111\74\0\3\61\72\0"+
    "\3\62\72\0\3\26\5\0\3\26\1\112\11\26\2\0"+
    "\24\26\22\0\3\26\5\0\2\26\1\113\12\26\2\0"+
    "\24\26\22\0\3\26\5\0\14\26\1\114\2\0\24\26"+
    "\22\0\3\26\5\0\15\115\2\0\24\115\22\0\3\26"+
    "\5\0\5\26\1\116\7\26\2\0\24\26\20\0\1\117"+
    "\1\0\3\74\5\0\15\26\2\0\24\26\22\0\3\26"+
    "\5\0\15\26\2\0\20\26\1\120\3\26\22\0\3\26"+
    "\5\0\15\26\2\0\1\26\1\121\22\26\22\0\3\26"+
    "\5\0\15\26\2\0\15\26\1\122\6\26\22\0\3\26"+
    "\5\0\15\26\2\0\17\26\1\123\4\26\22\0\3\26"+
    "\5\0\15\26\2\0\10\26\1\124\2\26\1\125\10\26"+
    "\22\0\3\26\5\0\15\26\2\0\13\26\1\126\10\26"+
    "\22\0\3\26\5\0\15\26\2\0\20\26\1\127\3\26"+
    "\22\0\3\26\5\0\15\26\2\0\20\26\1\130\3\26"+
    "\22\0\3\26\5\0\15\26\2\0\15\26\1\131\6\26"+
    "\22\0\3\26\5\0\15\26\2\0\13\26\1\132\10\26"+
    "\3\0\11\107\1\133\74\107\1\133\4\107\1\134\56\107"+
    "\17\0\3\26\5\0\4\26\1\135\10\26\2\0\24\26"+
    "\22\0\3\26\5\0\6\26\1\114\6\26\2\0\24\26"+
    "\22\0\3\26\3\0\1\136\1\0\15\115\2\0\24\115"+
    "\22\0\3\26\5\0\6\26\1\137\6\26\2\0\24\26"+
    "\22\0\3\117\72\0\3\26\5\0\15\26\2\0\7\26"+
    "\1\140\14\26\22\0\3\26\5\0\15\26\2\0\11\26"+
    "\1\141\12\26\22\0\3\26\5\0\15\26\2\0\1\26"+
    "\1\142\22\26\22\0\3\26\5\0\15\26\2\0\4\26"+
    "\1\143\17\26\22\0\3\26\5\0\15\26\2\0\1\26"+
    "\1\144\22\26\22\0\3\26\5\0\15\26\2\0\1\26"+
    "\1\145\22\26\22\0\3\26\5\0\15\26\2\0\4\26"+
    "\1\146\17\26\22\0\3\26\5\0\15\26\2\0\4\26"+
    "\1\147\17\26\22\0\3\26\5\0\15\26\2\0\1\26"+
    "\1\150\22\26\22\0\3\26\5\0\15\26\2\0\4\26"+
    "\1\151\17\26\22\0\3\26\5\0\15\26\2\0\14\26"+
    "\1\152\7\26\3\0\11\107\1\133\4\107\1\3\56\107"+
    "\17\0\3\26\5\0\12\26\1\153\2\26\2\0\24\26"+
    "\22\0\3\26\5\0\2\26\1\154\12\26\2\0\24\26"+
    "\22\0\3\26\5\0\15\26\2\0\22\26\1\155\1\26"+
    "\22\0\3\26\5\0\15\26\2\0\21\26\1\156\2\26"+
    "\22\0\3\26\5\0\15\26\2\0\13\26\1\157\10\26"+
    "\22\0\1\26\1\160\1\26\5\0\15\26\2\0\24\26"+
    "\22\0\3\26\5\0\15\26\2\0\16\26\1\161\5\26"+
    "\22\0\3\26\5\0\15\26\2\0\11\26\1\162\12\26"+
    "\22\0\3\26\5\0\15\26\2\0\16\26\1\163\5\26"+
    "\22\0\3\26\5\0\15\26\2\0\16\26\1\164\5\26"+
    "\22\0\3\26\5\0\15\26\2\0\16\26\1\165\5\26"+
    "\22\0\3\26\5\0\15\26\2\0\20\26\1\166\3\26"+
    "\22\0\3\26\5\0\1\114\14\26\2\0\24\26\22\0"+
    "\3\26\5\0\13\26\1\114\1\26\2\0\24\26\22\0"+
    "\3\26\5\0\15\26\2\0\1\26\1\167\22\26\22\0"+
    "\3\26\5\0\15\26\2\0\1\26\1\170\22\26\22\0"+
    "\3\26\5\0\15\26\2\0\3\26\1\171\20\26\22\0"+
    "\3\26\5\0\15\26\2\0\1\172\23\26\22\0\3\26"+
    "\5\0\15\26\2\0\1\26\1\173\22\26\22\0\3\26"+
    "\5\0\15\26\2\0\16\26\1\174\5\26\22\0\3\26"+
    "\5\0\15\26\2\0\7\26\1\175\14\26\22\0\3\26"+
    "\5\0\15\26\2\0\16\26\1\176\5\26\22\0\3\26"+
    "\5\0\15\26\2\0\16\26\1\177\5\26\22\0\3\26"+
    "\5\0\15\26\2\0\7\26\1\200\14\26\22\0\3\26"+
    "\5\0\13\26\1\201\1\26\2\0\24\26\22\0\3\26"+
    "\5\0\15\26\2\0\16\26\1\202\5\26\22\0\3\26"+
    "\5\0\15\26\2\0\21\26\1\203\2\26\22\0\3\26"+
    "\5\0\15\26\2\0\16\26\1\204\5\26\22\0\3\26"+
    "\5\0\15\26\2\0\16\26\1\205\5\26\22\0\3\26"+
    "\5\0\15\26\2\0\16\26\1\206\5\26\22\0\3\26"+
    "\5\0\15\26\2\0\1\207\23\26\22\0\3\26\5\0"+
    "\15\26\2\0\12\26\1\210\11\26\22\0\3\26\5\0"+
    "\11\26\1\211\3\26\2\0\24\26\22\0\3\26\5\0"+
    "\15\26\2\0\7\26\1\212\14\26\22\0\3\26\5\0"+
    "\15\26\2\0\6\26\1\213\15\26\22\0\3\26\5\0"+
    "\15\26\2\0\15\26\1\214\6\26\22\0\3\26\5\0"+
    "\15\26\2\0\7\26\1\215\14\26\22\0\3\26\5\0"+
    "\15\26\2\0\6\26\1\216\15\26\22\0\3\26\5\0"+
    "\15\26\2\0\16\26\1\217\5\26\22\0\3\26\5\0"+
    "\15\26\2\0\7\26\1\220\14\26\22\0\3\26\5\0"+
    "\15\26\2\0\4\26\1\221\17\26\22\0\3\26\5\0"+
    "\15\26\2\0\4\26\1\222\17\26\22\0\3\26\5\0"+
    "\15\26\2\0\1\26\1\223\22\26\22\0\3\26\5\0"+
    "\15\26\2\0\16\26\1\224\5\26\22\0\3\26\5\0"+
    "\15\26\2\0\13\26\1\225\10\26\22\0\3\26\5\0"+
    "\15\26\2\0\13\26\1\226\10\26\22\0\3\26\5\0"+
    "\15\26\2\0\5\26\1\227\16\26\22\0\3\26\5\0"+
    "\15\26\2\0\20\26\1\230\3\26\22\0\3\26\5\0"+
    "\15\26\2\0\16\26\1\231\5\26\22\0\3\26\5\0"+
    "\15\26\2\0\1\26\1\232\22\26\22\0\3\26\5\0"+
    "\15\26\2\0\17\26\1\233\4\26\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7259];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\5\11\1\1\1\11\3\1\2\11"+
    "\12\1\2\11\10\1\4\11\1\1\1\11\1\0\1\1"+
    "\1\0\1\11\2\1\3\11\5\1\1\11\13\1\2\0"+
    "\1\11\21\1\1\0\2\1\1\11\75\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
            // fall through
          case 44: break;
          case 2:
            { /* Ignorar */
            }
            // fall through
          case 45: break;
          case 3:
            { return token(yytext(), "OP_LOGICO", yyline, yycolumn);
            }
            // fall through
          case 46: break;
          case 4:
            { return token(yytext(), "PARENTESIS_A", yyline, yycolumn);
            }
            // fall through
          case 47: break;
          case 5:
            { return token(yytext(), "PARENTESIS_C", yyline, yycolumn);
            }
            // fall through
          case 48: break;
          case 6:
            { return token(yytext(), "MULTIPLICACION", yyline, yycolumn);
            }
            // fall through
          case 49: break;
          case 7:
            { return token(yytext(), "SUMA", yyline, yycolumn);
            }
            // fall through
          case 50: break;
          case 8:
            { return token(yytext(), "COMA", yyline, yycolumn);
            }
            // fall through
          case 51: break;
          case 9:
            { return token(yytext(), "RESTA", yyline, yycolumn);
            }
            // fall through
          case 52: break;
          case 10:
            { return token(yytext(), "PUNTO", yyline, yycolumn);
            }
            // fall through
          case 53: break;
          case 11:
            { return token(yytext(), "DIVISION", yyline, yycolumn);
            }
            // fall through
          case 54: break;
          case 12:
            { return token(yytext(), "N_ENTERO", yyline, yycolumn);
            }
            // fall through
          case 55: break;
          case 13:
            { return token(yytext(), "DOBLE_PUNTO", yyline, yycolumn);
            }
            // fall through
          case 56: break;
          case 14:
            { return token(yytext(), "PUNTOyCOMA", yyline, yycolumn);
            }
            // fall through
          case 57: break;
          case 15:
            { return token(yytext(), "MENOR_QUE", yyline, yycolumn);
            }
            // fall through
          case 58: break;
          case 16:
            { return token(yytext(), "MAYOR_QUE", yyline, yycolumn);
            }
            // fall through
          case 59: break;
          case 17:
            { return token(yytext(), "ERROR_2", yyline, yycolumn);
            }
            // fall through
          case 60: break;
          case 18:
            { return token(yytext(), "CORCHETE_A", yyline, yycolumn);
            }
            // fall through
          case 61: break;
          case 19:
            { return token(yytext(), "CORCHETE_C", yyline, yycolumn);
            }
            // fall through
          case 62: break;
          case 20:
            { return token(yytext(), "LLAVE_A", yyline, yycolumn);
            }
            // fall through
          case 63: break;
          case 21:
            { return token(yytext(), "LLAVE_C", yyline, yycolumn);
            }
            // fall through
          case 64: break;
          case 22:
            { return token(yytext(), "DIFERENTE_DE", yyline, yycolumn);
            }
            // fall through
          case 65: break;
          case 23:
            { return token(yytext(), "IDENTIFICADOR", yyline, yycolumn);
            }
            // fall through
          case 66: break;
          case 24:
            { return token(yytext(), "Op_Asig", yyline, yycolumn);
            }
            // fall through
          case 67: break;
          case 25:
            { return token(yytext(), "ERROR_1", yyline, yycolumn);
            }
            // fall through
          case 68: break;
          case 26:
            { return token(yytext(), "N_DECIMAL", yyline, yycolumn);
            }
            // fall through
          case 69: break;
          case 27:
            { return token(yytext(), "MENOR_IGUAL_QUE", yyline, yycolumn);
            }
            // fall through
          case 70: break;
          case 28:
            { return token(yytext(), "IGUAL_QUE", yyline, yycolumn);
            }
            // fall through
          case 71: break;
          case 29:
            { return token(yytext(), "MAYOR_IGUAL_QUE", yyline, yycolumn);
            }
            // fall through
          case 72: break;
          case 30:
            { return token(yytext(), "TEMPERATURA", yyline, yycolumn);
            }
            // fall through
          case 73: break;
          case 31:
            { return token(yytext(), "ESTRUCTURA_SI", yyline, yycolumn);
            }
            // fall through
          case 74: break;
          case 32:
            { return token(yytext(), "TIPO_DATO", yyline, yycolumn);
            }
            // fall through
          case 75: break;
          case 33:
            { return token(yytext(), "CADENA", yyline, yycolumn);
            }
            // fall through
          case 76: break;
          case 34:
            { return token(yytext(), "FASES", yyline, yycolumn);
            }
            // fall through
          case 77: break;
          case 35:
            { return token(yytext(), "FINAL", yyline, yycolumn);
            }
            // fall through
          case 78: break;
          case 36:
            { return token(yytext(), "FUNCION_MUTAR", yyline, yycolumn);
            }
            // fall through
          case 79: break;
          case 37:
            { return token (yytext(), "ACTIVAR", yyline, yycolumn);
            }
            // fall through
          case 80: break;
          case 38:
            { return token(yytext(), "EVALUAR", yyline, yycolumn);
            }
            // fall through
          case 81: break;
          case 39:
            { return token(yytext(), "REPETIR", yyline, yycolumn);
            }
            // fall through
          case 82: break;
          case 40:
            { return token(yytext(), "EXPANDIR", yyline, yycolumn);
            }
            // fall through
          case 83: break;
          case 41:
            { return token(yytext(), "DETENER_REPETIR", yyline, yycolumn);
            }
            // fall through
          case 84: break;
          case 42:
            { return token(yytext(), "FUNCION FIJAR_ORIGEN", yyline, yycolumn);
            }
            // fall through
          case 85: break;
          case 43:
            { return token(yytext(), "GENERAR_GRAF", yyline, yycolumn);
            }
            // fall through
          case 86: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
