// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/LexerColor.flex


import compilerTools.TextColor;
import java.awt.Color;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class LexerColor {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\1\2\1\0\1\3\23\0\1\4\4\0"+
    "\1\5\1\0\2\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\6\16\3\17\2\11\1\4\1\20\1\4"+
    "\2\0\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\22\1\30\1\22\1\31\1\32\1\33\1\34\1\35"+
    "\2\22\1\36\1\37\1\40\1\22\1\41\4\22\1\6"+
    "\1\0\1\6\1\0\1\42\1\0\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\22\1\52\1\53\1\22"+
    "\1\54\1\55\1\56\1\57\1\60\1\22\1\61\1\62"+
    "\1\63\1\64\1\65\1\22\1\66\2\22\1\6\1\10"+
    "\1\6\7\0\1\2\113\0\1\22\17\0\1\22\7\0"+
    "\1\22\3\0\1\22\3\0\1\22\1\0\1\22\6\0"+
    "\1\22\u012d\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\2\2\1\3\1\2\1\4\2\2\2\5"+
    "\25\1\1\6\1\0\1\7\10\1\2\10\16\1\1\11"+
    "\2\0\2\7\2\1\1\10\1\1\1\12\2\1\1\0"+
    "\1\10\17\1\1\0\1\7\17\1\1\11\10\1\1\13"+
    "\1\1\1\14\16\1\1\15\3\1\1\11\15\1\1\5"+
    "\6\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\67\0\67\0\67"+
    "\0\u0113\0\u014a\0\u0181\0\u01b8\0\245\0\u01ef\0\u0226\0\u025d"+
    "\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415"+
    "\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd"+
    "\0\u0604\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785"+
    "\0\u07bc\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d"+
    "\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5"+
    "\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\67"+
    "\0\u0cad\0\u0ce4\0\u0d1b\0\u01ef\0\u0d52\0\u07f3\0\u0d89\0\u0dc0"+
    "\0\u0df7\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41"+
    "\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9"+
    "\0\u1130\0\u1167\0\u0c3f\0\u119e\0\u11d5\0\u120c\0\u1243\0\u127a"+
    "\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432"+
    "\0\u1469\0\u14a0\0\u01ef\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3"+
    "\0\u15ea\0\u1621\0\u1658\0\u01ef\0\u168f\0\u01ef\0\u16c6\0\u16fd"+
    "\0\u1734\0\u176b\0\u17a2\0\u17d9\0\u1810\0\u1847\0\u187e\0\u18b5"+
    "\0\u18ec\0\u1923\0\u195a\0\u1991\0\u01ef\0\u19c8\0\u19ff\0\u1a36"+
    "\0\u1a6d\0\u1aa4\0\u1adb\0\u1b12\0\u1b49\0\u1b80\0\u1bb7\0\u1bee"+
    "\0\u1c25\0\u1c5c\0\u1c93\0\u1cca\0\u1d01\0\u1d38\0\u01ef\0\u1d6f"+
    "\0\u1da6\0\u1ddd\0\u1e14\0\u1e4b\0\u1e82";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\0\1\3\1\4\1\5\1\6\2\7\1\10"+
    "\1\11\1\10\1\12\1\13\2\14\1\15\2\16\1\17"+
    "\1\20\1\21\1\22\2\16\1\23\1\24\1\16\1\25"+
    "\3\16\1\26\1\27\1\16\1\30\3\16\1\31\1\32"+
    "\1\33\1\34\1\16\1\35\1\36\1\37\2\16\1\40"+
    "\1\41\4\16\70\0\1\2\105\0\1\7\67\0\46\42"+
    "\13\0\1\7\62\0\1\43\4\0\1\44\67\0\1\2"+
    "\2\45\64\0\3\14\64\0\3\16\1\0\46\16\15\0"+
    "\3\16\1\0\1\46\45\16\15\0\3\16\1\0\4\16"+
    "\1\47\41\16\15\0\3\16\1\0\13\16\1\50\32\16"+
    "\15\0\3\16\1\0\1\51\45\16\15\0\3\16\1\0"+
    "\21\16\1\52\24\16\15\0\3\16\1\0\14\16\1\53"+
    "\31\16\15\0\3\16\1\0\43\16\1\54\2\16\15\0"+
    "\1\55\2\56\1\0\46\16\15\0\3\16\1\0\4\16"+
    "\1\57\41\16\15\0\3\16\1\0\24\16\1\60\13\16"+
    "\1\61\5\16\15\0\3\16\1\0\41\16\1\62\2\16"+
    "\1\63\1\64\15\0\3\16\1\0\22\16\1\65\6\16"+
    "\1\66\14\16\15\0\3\16\1\0\26\16\1\67\17\16"+
    "\15\0\3\16\1\0\35\16\1\70\10\16\15\0\3\16"+
    "\1\0\26\16\1\71\17\16\15\0\3\16\1\0\43\16"+
    "\1\72\2\16\15\0\3\16\1\0\43\16\1\73\2\16"+
    "\15\0\3\16\1\0\26\16\1\74\17\16\15\0\3\16"+
    "\1\0\31\16\1\75\14\16\15\0\3\42\1\0\46\42"+
    "\7\76\1\77\57\76\1\44\1\100\1\44\1\101\63\44"+
    "\15\0\3\45\64\0\3\16\1\0\3\16\1\102\42\16"+
    "\15\0\3\16\1\0\2\16\1\103\43\16\15\0\3\16"+
    "\1\0\17\16\1\104\26\16\15\0\3\16\1\0\11\16"+
    "\1\105\34\16\15\0\3\16\1\0\46\106\15\0\3\16"+
    "\1\0\6\16\1\107\37\16\15\0\3\16\1\0\34\16"+
    "\1\110\11\16\13\0\1\111\1\0\3\16\1\0\46\16"+
    "\13\0\1\112\1\0\3\56\1\0\46\16\15\0\3\16"+
    "\1\0\15\16\1\113\30\16\15\0\3\16\1\0\42\16"+
    "\1\114\3\16\15\0\3\16\1\0\40\16\1\115\5\16"+
    "\15\0\3\16\1\0\24\16\1\116\21\16\15\0\3\16"+
    "\1\0\22\16\1\117\23\16\15\0\3\16\1\0\37\16"+
    "\1\120\6\16\15\0\3\16\1\0\41\16\1\121\4\16"+
    "\15\0\3\16\1\0\32\16\1\122\2\16\1\123\10\16"+
    "\15\0\3\16\1\0\35\16\1\124\10\16\15\0\3\16"+
    "\1\0\42\16\1\125\3\16\15\0\3\16\1\0\26\16"+
    "\1\126\17\16\15\0\3\16\1\0\42\16\1\127\3\16"+
    "\15\0\3\16\1\0\33\16\1\130\12\16\15\0\3\16"+
    "\1\0\37\16\1\131\6\16\15\0\3\16\1\0\35\16"+
    "\1\130\10\16\7\76\1\132\66\76\1\132\4\76\1\133"+
    "\52\76\1\0\1\100\102\0\3\16\1\0\4\16\1\134"+
    "\41\16\15\0\3\16\1\0\7\16\1\104\36\16\15\0"+
    "\3\16\1\0\16\16\1\135\27\16\15\0\3\16\1\0"+
    "\7\16\1\136\36\16\15\0\3\16\1\0\26\16\1\137"+
    "\17\16\15\0\3\112\64\0\3\16\1\0\3\16\1\140"+
    "\42\16\15\0\3\16\1\0\31\16\1\141\14\16\15\0"+
    "\3\16\1\0\26\16\1\142\17\16\15\0\3\16\1\0"+
    "\40\16\1\143\5\16\15\0\3\16\1\0\33\16\1\144"+
    "\12\16\15\0\3\16\1\0\22\16\1\145\23\16\15\0"+
    "\3\16\1\0\26\16\1\146\17\16\15\0\3\16\1\0"+
    "\22\16\1\147\23\16\15\0\3\16\1\0\22\16\1\150"+
    "\23\16\15\0\3\16\1\0\26\16\1\151\17\16\15\0"+
    "\3\16\1\0\26\16\1\152\17\16\15\0\3\16\1\0"+
    "\40\16\1\153\5\16\15\0\3\16\1\0\22\16\1\154"+
    "\23\16\15\0\3\16\1\0\36\16\1\153\7\16\15\0"+
    "\3\16\1\0\26\16\1\155\17\16\7\76\1\132\4\76"+
    "\1\100\52\76\15\0\3\16\1\0\13\16\1\156\32\16"+
    "\15\0\3\16\1\0\14\16\1\104\31\16\15\0\3\16"+
    "\1\0\2\16\1\135\43\16\15\0\3\16\1\0\40\16"+
    "\1\157\5\16\15\0\3\16\1\0\1\160\45\16\15\0"+
    "\3\16\1\0\44\16\1\161\1\16\15\0\3\16\1\0"+
    "\30\16\1\73\15\16\15\0\3\16\1\0\31\16\1\162"+
    "\14\16\15\0\3\16\1\0\43\16\1\127\2\16\15\0"+
    "\3\16\1\0\35\16\1\163\10\16\15\0\1\16\1\164"+
    "\1\16\1\0\46\16\15\0\3\16\1\0\40\16\1\165"+
    "\5\16\15\0\3\16\1\0\33\16\1\166\12\16\15\0"+
    "\3\16\1\0\40\16\1\167\5\16\15\0\3\16\1\0"+
    "\40\16\1\170\5\16\15\0\3\16\1\0\40\16\1\164"+
    "\5\16\15\0\3\16\1\0\42\16\1\171\3\16\15\0"+
    "\3\16\1\0\1\104\45\16\15\0\3\16\1\0\36\16"+
    "\1\172\7\16\15\0\3\16\1\0\3\16\1\173\42\16"+
    "\15\0\3\16\1\0\22\16\1\174\23\16\15\0\3\16"+
    "\1\0\23\16\1\175\22\16\15\0\3\16\1\0\25\16"+
    "\1\176\20\16\15\0\3\16\1\0\21\16\1\177\24\16"+
    "\15\0\3\16\1\0\22\16\1\200\23\16\15\0\3\16"+
    "\1\0\40\16\1\201\5\16\15\0\3\16\1\0\31\16"+
    "\1\202\14\16\15\0\3\16\1\0\21\16\1\203\24\16"+
    "\15\0\3\16\1\0\4\16\1\204\41\16\15\0\3\16"+
    "\1\0\40\16\1\205\5\16\15\0\3\16\1\0\31\16"+
    "\1\126\14\16\15\0\3\16\1\0\31\16\1\154\14\16"+
    "\15\0\3\16\1\0\14\16\1\206\31\16\15\0\3\16"+
    "\1\0\40\16\1\207\5\16\15\0\3\16\1\0\43\16"+
    "\1\210\2\16\15\0\3\16\1\0\40\16\1\211\5\16"+
    "\15\0\3\16\1\0\25\16\1\212\20\16\15\0\3\16"+
    "\1\0\15\16\1\135\30\16\15\0\3\16\1\0\40\16"+
    "\1\213\5\16\15\0\3\16\1\0\21\16\1\214\24\16"+
    "\15\0\3\16\1\0\34\16\1\215\11\16\15\0\3\16"+
    "\1\0\12\16\1\216\33\16\15\0\3\16\1\0\26\16"+
    "\1\217\17\16\15\0\3\16\1\0\31\16\1\220\14\16"+
    "\15\0\3\16\1\0\30\16\1\221\15\16\15\0\3\16"+
    "\1\0\37\16\1\175\6\16\15\0\3\16\1\0\31\16"+
    "\1\222\14\16\15\0\3\16\1\0\24\16\1\223\21\16"+
    "\15\0\3\16\1\0\30\16\1\224\15\16\15\0\3\16"+
    "\1\0\40\16\1\225\5\16\15\0\3\16\1\0\26\16"+
    "\1\226\17\16\15\0\3\16\1\0\31\16\1\227\14\16"+
    "\15\0\3\16\1\0\26\16\1\230\17\16\15\0\3\16"+
    "\1\0\22\16\1\231\23\16\15\0\3\16\1\0\35\16"+
    "\1\232\10\16\15\0\3\16\1\0\35\16\1\164\10\16"+
    "\15\0\3\16\1\0\27\16\1\164\16\16\15\0\3\16"+
    "\1\0\42\16\1\233\3\16\15\0\3\16\1\0\40\16"+
    "\1\234\5\16\15\0\3\16\1\0\22\16\1\235\23\16"+
    "\15\0\3\16\1\0\41\16\1\153\4\16";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7865];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\3\11\32\1\1\0\32\1\2\0"+
    "\1\11\10\1\1\0\20\1\1\0\103\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private TextColor textColor(long start, int size, Color color){
        return new TextColor((int)start, size, color);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerColor(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public TextColor yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* Ignorar */
            }
            // fall through
          case 14: break;
          case 2:
            { return textColor(yychar, yylength(), new Color(255, 265, 0));
            }
            // fall through
          case 15: break;
          case 3:
            { return textColor(yychar, yylength(), new Color(19, 53, 114));
            }
            // fall through
          case 16: break;
          case 4:
            { return textColor(yychar, yylength(), new Color(0, 0, 0));
            }
            // fall through
          case 17: break;
          case 5:
            { return textColor(yychar, yylength(), new Color(35, 120, 147));
            }
            // fall through
          case 18: break;
          case 6:
            { return textColor(yychar, yylength(), new Color(255, 200, 0));
            }
            // fall through
          case 19: break;
          case 7:
            { return textColor(yychar, yylength(), new Color(146, 146, 146));
            }
            // fall through
          case 20: break;
          case 8:
            { return textColor(yychar, yylength(), new Color(0, 0, 255));
            }
            // fall through
          case 21: break;
          case 9:
            { return textColor(yychar, yylength(), new Color(102, 205, 170));
            }
            // fall through
          case 22: break;
          case 10:
            { return textColor(yychar, yylength(), new Color(255, 0, 255));
            }
            // fall through
          case 23: break;
          case 11:
            { return textColor(yychar, yylength(), new Color(0, 144, 255));
            }
            // fall through
          case 24: break;
          case 12:
            { return textColor(yychar, yylength(), new Color(255, 0, 0));
            }
            // fall through
          case 25: break;
          case 13:
            { return textColor(yychar, yylength(), new Color(225, 181, 29));
            }
            // fall through
          case 26: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
